### ISSUE TITLE
Leerzeichen in SSID wird nicht erkannt

### ISSUE THREAD

**Issue by LinkmanVN** [Eisbaeeer/Ulrich-Radig_Wort_Uhr_Version_2#3]
Leerzeichen in SSID wird ignoriert und nicht gespeichert.

**Comment by Eisbaeeer** [comment]
Bitte mal mit Anführungszeichen testen und nochmals Rückmeldung geben. Danke.

**Comment by LinkmanVN** [comment]
Woll soll ich das Anführungszeichen einsetzen?
z.B SSID: "**Wort Uhr**" wird nicht funktionieren. 
Ohne Leerzeichen "**WortUhr**" wird die Verbindung hergestellt.

**Comment by LinkmanVN** [comment]
Das war eigt. die Kinderkrankheit von V2

**Comment by Eisbaeeer** [comment]
Hab die Stelle gefunden, bei dem der Fehler entsteht. Ich schau mir das an, kann aber noch nicht versprechen wie schnell das beseitigt ist. Brauche erst ein Test WLAN, da ich meines nicht so einfach ändern kann/will.

**Comment by LinkmanVN** [comment]
Wow, das ist nice.
Vllt kannst du Gast-Zugang am Router einrichten und testen

**Comment by Eisbaeeer** [comment]
Solved in Version 2.0.11
