### ISSUE TITLE
In welchen Pin WS2812B LEDs. 

### ISSUE THREAD

**Issue by patafix18** [Eisbaeeer/Ulrich-Radig_Wort_Uhr_Version_2#5]
Hallo,
an welchen Pin der NodeMCU 8266 werden die WS2812B LEDs angeschlossen?
In der Dokumentation finde ich dazu leider nichts aktuelles und im Arduino Code bin ich auch nicht fündig geworden. 
Schonmal vielen Dank. 
Patrick

**Comment by Eisbaeeer** [comment]
Hallo
Du findest das in der Datei Uhr.h Zeile 164
`const uint8_t PixelPin = 2;  // WS2812 Data Port`
Ich werde das noch in der Doku ergänzen.
