### ISSUE TITLE
Reboot nach Aufruf der Konfigseite

### ISSUE THREAD

**Issue by dbambus** [Eisbaeeer/Ulrich-Radig_Wort_Uhr_Version_2#7]
Hallo, 

erst einmal ein sehr guter Code für die eigene DIY-Wordclock. 

Ich habe derzeit ein Problem mit der Konfigseite, denn wenn ich diese Aufrufe, um zum Beispiel meine WLAN Daten einzugeben, dann Rebooted der ESP8266 ohne erkennbaren Grund. Am Code selbst habe ich nichts geändert, ein reiner git-clone sozusagen. Deine Binary-Version funktioniert ohne Probleme. Könntest du für weiteres Debuggen deine Arduino Board Settings teilen ?

Ich habe den Sketch an zwei ESP8266 getestet, auch mit diversen Flash-Settings, jedoch keine Besserung. 

Meine Compiledte Version
```
--------------------------------------
ESP Uhr
Version         : 2.1.1
Chip ID         : 00003659
Flash ID        : 001640C8

CPU Speed       : 80 MHz 

Flash real Size : 4096 KByte
Flash ide  Size : 4096 KByte
Flash ide Speed : 40000000

Free Heap Size  : 35088 Byte
Sketch Size     : 372128 Byte 
Free Sketch Size: 675840 Byte 

SDK Version     : 2.2.1(cfd48f3)
RESET Info      : Fatal exception:4 flag:1 (WDT) epc1:0x40210c48 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
COMPILED        : Jan 25 2019 18:10:33
--------------------------------------
```

Dein Original .bin
```
--------------------------------------
ESP Uhr
Version         : 2.1.1
Chip ID         : 00003659
Flash ID        : 001640C8

CPU Speed       : 80 MHz 

Flash real Size : 4096 KByte
Flash ide  Size : 4096 KByte
Flash ide Speed : 40000000

Free Heap Size  : 28896 Byte
Sketch Size     : 332080 Byte 
Free Sketch Size: 712704 Byte 

SDK Version     : 1.5.3(aec24ac9)
RESET Info      : Fatal exception:0 flag:4 (SOFT_RESTART) epc1:0x00000000 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
COMPILED        : Jan  6 2019 21:53:10
--------------------------------------
```

**Comment by dbambus** [comment]
Guten Tag, 

ich habe etwas rumgetestet und Settings gefunden die funktionieren.
ESP8266 V2.3.0
Neopixelbus V2.3.0

Könnte man die Main updaten, sodass es auch die aktuellen, stabilen Versionen der Librarys unterstützt werden ?

**Comment by dbambus** [comment]
@Giittie 
Hallo, probiere mal in der Version 2.1.1 die WLAN Zugangsdaten in den Zeilen 162/163 fest einzutragen. Läuft der Code anschließend auch stabil ?

**Comment by Eisbaeeer** [comment]
Hallo zusammen.
Das mit der SSID und Leerzeichen wundert mich jetzt. Das hatte ich schon mal gefixt. Muss wohl dann bei einem pull-request wieder reingekommen sein. Schau ich mal nach,  bei welcher Version das war. 
@dbambus: deine lauffähigen Einstellungen wären interessant. Klar kann man die main anpassen. Gerne auch du selbst und einen pull request. Jeder darf mitentwickeln. Ist Open Source.

**Comment by Giittie** [comment]
Hallo zusammen,
erstmal Danke für eure schnelle Hilfe.

Wie von dbambus vorgeschlagen habe ich in der Datei Wortuhr…….ino Version 2.1.1 in der Zeile WiFi.begin meine SSID und Passwort eingetragen und mit ESP8266 Version 2.4.2 und Adafruit_Neopixel Version 1.1.8 kompiliert: im seriellen Monitor wird die richtige Zeit angezeigt. Die LEDs habe ich zur Zeit noch nicht angeschlossen.

Auch mit der ESP8266 Version 2.3.0, wie weiter oben von dbambus vorgeschlagen, habe ich alles kompiliert. Auch hier wird die Uhrzeit richtig im seriellen Monitor angezeigt.

Es scheint also noch ein Problem im ESP AP Modus zu geben.

Über eine Rückmeldung würde ich mich freuen.

**Comment by JoakimSelander** [comment]
Sorry don't speek german but I found the problem. Don't know why it worked on older versions.
But you should change uhr.h line 199 from "char s[3];" to "char s[5];"
This is because s can contain "100" so it will crash on line 883 in Uhr_Neu.ino

**Comment by dbambus** [comment]
With the changes suggested by @JoakimSelander it works, also with the latest versions of the library.
